.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH remove 1  "remove " 
.SH NAME
remove \- 从监控列表中删除一个或多个本地 Git 仓库
.SH SYNOPSIS
\fBskillsync remove\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPATHS\fR] 
.SH DESCRIPTION
从监控列表中删除一个或多个本地 Git 仓库
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATHS\fR]
仓库的本地路径，支持多个
